credentials:
  usernames:
    mehran:
      email: mehran@gmail.com
      name: Mehran
      password: '$2b$12$RvVKhB86jsX6LFIjPCqHGeOc.nKMQ37Xu8EtC0IFjmZCBL3hJyKqy' 
    alexshrake:
      email: aj@gmail.com
      name: Alex Shrake
      password: '$2b$12$wGMh1R/tZnQvBesTpNqWauxdsGetCoo.BSWaXrhFNPPJruInKYuKO' 
    thaliaaspeslet:
      email: thaliaaspeslet@gmail.com
      name: Thalia Aspeslet
      password: '$2b$12$hvGr6aw6xG7b2qZa7glsM.zxMU4zNyLJrWvVcGGmk4zWcNdGwWjNm'
    heatherbishop:
      email: heatherbishop@gmail.com
      name: Heather Bishop
      password: '$2b$12$GrJNSVDTYf.BhWjDposDLusfbg8f6MEJf7jCAow2i1Epa46BG2X3G'
    kylemartin:
      email: kylemartin@gmail.com
      name: Kyle Martin
      password: '$2b$12$GrJNSVDTYf.BhWjDposDLusfbg8f6MEJf7jCAow2i1Epa46BG2X3G'
    byronfraser:
      email: byronfraser@gmail.com
      name: Byron Fraser
      password: '$2b$12$Hf7WWxu9FuVR1ZIaLZndr.CYxP5U.JY2Lf0jNiBz/50P9FCQVKNxW'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
